#!/bin/bash

HOST_NAME=jeanzay

PORT_MLFLOW_UI_HOST=5000
PORT_MLFLOW_UI_LOCAL=5001
REMOTE_HOST_MLFLOW_UI="0.0.0.0"

PORT_TENSORBOARD_HOST=6006
PORT_TENSORBOARD_LOCAL=6007
REMOTE_HOST_TENSORBOARD="localhost"

echo "Forwarding ports:"
echo
echo "PORT_MLFLOW_UI_HOST: $PORT_MLFLOW_UI_HOST"
echo "PORT_MLFLOW_UI_LOCAL: $PORT_MLFLOW_UI_LOCAL"
echo "REMOTE_HOST_MLFLOW_UI: $REMOTE_HOST_MLFLOW_UI"
echo

echo
echo "PORT_TENSORBOARD_HOST: $PORT_TENSORBOARD_HOST"
echo "PORT_TENSORBOARD_LOCAL: $PORT_TENSORBOARD_LOCAL"
echo "REMOTE_HOST_TENSORBOARD: $REMOTE_HOST_TENSORBOARD"
echo

ssh -N \
 -L "$PORT_MLFLOW_UI_LOCAL":$REMOTE_HOST_MLFLOW_UI:"$PORT_MLFLOW_UI_HOST" \
 -L "$PORT_TENSORBOARD_LOCAL":$REMOTE_HOST_TENSORBOARD:"$PORT_TENSORBOARD_HOST" \
$HOST_NAME
